In [ ]:
## Q.1  What is a Python library? Why  we use Python libraries?
Python library is a collection of code that make every day task more efficient 
using matplotlib we can create visualization of data

In [ ]:
## 2. What is the difference between Numpy array and List?
Numbai array of ark are much faster than list restore one type of data but least store mixed data numpy array 
used for advanced mathematically and on large number of data list can be homogeneous and heterogeneous

In [21]:
## 3. Find the shape, size and dimension of the following array?
([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]])
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr.ndim

2

In [26]:
arr.shape

(3, 4)

In [27]:
arr.size

12

In [ ]:
## 4. Write python code to access the first row of the following array?
([[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]])


In [33]:
import numpy as np
arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr1[0]

array([1, 2, 3, 4])

In [35]:
## 5. How do you access the element at the second row and third column from the given numpy array?
arr1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr1[2][3]

12

In [40]:
## 6. Write code to extract all odd-indexed elements from the given numpy array?

arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:

def oddindex(arr1,row,col,n):
    row=0
    col=0
    for i in range(len(arr1)):
        for col in range(len(arr1)):
             if arr1[row][col]!=0:
                print(arr1)

In [56]:
oddindex(arr1,0,0,12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
## 7. How can you generate a random 3x3 matrix with values between 0 and 1?
np.random.randint(0,1,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
## 8. Describe the difference between np.random.rand and np.random.randn?


In [61]:
## 9. Write code to increase the dimension of the following array?
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
np.expand_dims(arr1,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [63]:
np.expand_dims(arr1,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [65]:
## 10. How to transpose the following array in NumPy?


arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [71]:
## 11. Consi^er the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Perform the following operation using Python1
 #Index wise multiplicatio'
## Matrix multiplication'
# Add both the maticK
 #Subtact matix B om 
 #Diide Matix B by A
     
arr2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [72]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [76]:
arr2-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
arr1*arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [78]:
arr2/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
## 12. Which function in Numpy can be used to swap the byte order of an array?
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
arr1.byteswap(True)

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

In [81]:
arr1.byteswap(False)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
## 13. What is the significance of the np.linalg.inv function?
python provides a very easy method to calculate the inverse of matrix  the function 
numpy.linalg.inv() is the available in numpy

In [ ]:
## 14. What does the np.reshape function do, and how is it used?
the np.reshape() of numpy do reshape the array ...but always size of previous array
thats mesn if we take a array of size(3,4),,,so we reshape it in (2,6) or(4,3) or(6,2)....thas mean always multiply
12 because previous array size is 12


In [ ]:
## 15. What is broadcasting in Numpy?

nampa Broadcasting is a set of principle