## Numpy

In [5]:
import numpy as np
np.__version__

'1.24.3'

In [31]:
print(np.__version__)

1.24.3


In [32]:
## why Numpy
l=[1,2,3,4,5]
arr=np.array(l)

In [33]:
arr

array([1, 2, 3, 4, 5])

In [34]:
type(np.array(l))

numpy.ndarray

In [35]:
np.array(l)

array([1, 2, 3, 4, 5])

In [36]:
arr.ndim

1

In [37]:
l=[1,2,3,4,'aaru']
arr1=np.array(l)

In [38]:
arr1

array(['1', '2', '3', '4', 'aaru'], dtype='<U11')

In [39]:
arr1=np.array([[1,2,3],[4,5,6]])

In [40]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
type(arr1)

numpy.ndarray

In [42]:
arr1.ndim

2

In [43]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [44]:
np.asanyarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [54]:
mat=np.matrix(l)

In [55]:
mat

matrix([['1', '2', '3', '4', 'aaru']], dtype='<U11')

In [58]:
np.asarray(mat)

array([['1', '2', '3', '4', 'aaru']], dtype='<U11')

In [59]:
l=[1,2,3,4,5]

In [61]:
mat=np.matrix(l)

In [62]:
mat

matrix([[1, 2, 3, 4, 5]])

In [63]:
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [64]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [65]:
t=([1,2,3],[4,5,6])

In [66]:
type(t)

tuple

In [67]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a=5

In [69]:
np.array(a)

array(5)

## Deep Copy  &  Shallow Copy

In [79]:
l=[1,2,3,4,5]

In [80]:
arr=np.array(l)

In [81]:
arr

array([1, 2, 3, 4, 5])

In [82]:
arr[0]

1

In [84]:
arr[4]

5

In [85]:
a=arr

In [86]:
a

array([1, 2, 3, 4, 5])

In [89]:
arr[0]=1000

In [90]:
arr

array([1000,    2,    3,    4,    5])

In [91]:
a

array([1000,    2,    3,    4,    5])

## Deep Copy

In [100]:
b=a.copy()

In [101]:
b[0]=2000

In [102]:
b

array([2000,    2,    3,    4,    5])

In [103]:
a

array([2000,    2,    3,    4,    5])

## How to genrate array

In [104]:
np.fromfunction(lambda i,j : i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [105]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr1.shape

(2, 3)

In [107]:
arr=[1,2,3,4,5]

In [110]:
arr.shape

AttributeError: 'list' object has no attribute 'shap'

In [109]:
arr.size

AttributeError: 'list' object has no attribute 'size'

In [111]:
np.fromfunction(lambda i,j : i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [112]:
range(5)

range(0, 5)

In [118]:
for i in range(5):
    print(i)

0
1
2
3
4


In [121]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [1]:
list(range(5))

[0, 1, 2, 3, 4]

In [2]:
iterable=(i*i for i in range(5))

In [6]:
iterable

<generator object <genexpr> at 0x000001C4A209D970>

In [9]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [10]:
np.fromstring("23 34 56",sep=' ')

array([23., 34., 56.])

In [21]:
arr=[1,2,3,4]

In [22]:
np.array(arr)

array([1, 2, 3, 4])

In [24]:
arr

[1, 2, 3, 4]

In [25]:
arr.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [14]:
l=[1,2,3,4,5]

In [16]:
arr=np.array(l)

In [17]:
arr.dtype

dtype('int32')

In [26]:
list(range(5))

[0, 1, 2, 3, 4]

In [27]:
range(5)

range(0, 5)

In [30]:
np.arange(0.1,10.4,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

In [164]:
np.linespace(1,5,base=2)                                                      # ask ques

AttributeError: module 'numpy' has no attribute 'linespace'

In [34]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

## Zeros

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
arr2=np.zeros((3,4))

In [43]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
arr3=np.zeros((3,3,4))

In [46]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
arr3.shape

(3, 3, 4)

In [48]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
arr=np.ones((3,4))

In [64]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
arr+4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## 21 jan advanced numpy

In [58]:
import numpy as np

In [59]:
np.array((3,4))

array([3, 4])

In [66]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## Empty()

In [71]:
np.empty((3,4),int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 5242972, 5177423],
       [4259914, 8257618,      49,       0]])

In [73]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [76]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
import pandas as pd

In [79]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [80]:
import random

In [81]:
random.choice((1,2,3,4,5,6))

5

In [82]:
random.randrange(1,100)

20

In [83]:
random.randrange(1,100)

26

In [84]:
random.random()

0.14325734738182427

In [85]:
list=[1,2,3,4,5]

In [92]:
random.shuffle(list)

In [93]:
list

[2, 4, 5, 1, 3]

In [94]:
random.uniform(7,14)

7.646711605634083

In [95]:
random.uniform(7,9)

8.767821554916315

In [96]:
np.random.rand(2,3)

array([[0.5677761 , 0.66799299, 0.40547133],
       [0.28240387, 0.11362724, 0.66615571]])

In [97]:
np.random.rand(2)

array([0.25817   , 0.18840165])

In [98]:
np.random.rand(1)

array([0.05049385])

In [100]:
np.random.random_sample()

0.38296164368092134

In [101]:
np.random.random_sample(2)

array([0.4519889 , 0.08106634])

In [102]:
np.random.randint(1,5,size=(3,4))

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 3]])

In [103]:
np.random.randint(1,5,size=(3,4))

array([[2, 1, 1, 2],
       [1, 3, 1, 4],
       [1, 4, 1, 2]])

In [104]:
np.random.randint(1,5,size=(3,4))

array([[1, 2, 1, 1],
       [4, 1, 3, 1],
       [2, 3, 1, 3]])

In [106]:
arr.reshape(2,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [108]:
arr.reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
arr.reshape(-1,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [112]:
arr.reshape(4,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [116]:
arr.reshape(3,4).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
arr.reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [119]:
arr.reshape(1,2,2,3)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

## reduce the dimention

In [121]:
np.random.randint(1,5,(5,6))

array([[3, 1, 4, 1, 1, 4],
       [2, 4, 1, 4, 4, 4],
       [4, 1, 4, 1, 4, 3],
       [3, 4, 4, 1, 3, 4],
       [1, 4, 3, 1, 2, 2]])

In [123]:
 arr1=np.random.randint(1,5,(5,6))

In [124]:
arr1

array([[4, 1, 1, 3, 2, 3],
       [4, 1, 4, 4, 2, 4],
       [2, 3, 1, 1, 3, 1],
       [3, 1, 2, 2, 1, 4],
       [2, 2, 4, 2, 4, 3]])

In [126]:
arr1>2

array([[ True, False, False,  True, False,  True],
       [ True, False,  True,  True, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False, False, False,  True],
       [False, False,  True, False,  True,  True]])

## how to access the ele

In [127]:
arr1

array([[4, 1, 1, 3, 2, 3],
       [4, 1, 4, 4, 2, 4],
       [2, 3, 1, 1, 3, 1],
       [3, 1, 2, 2, 1, 4],
       [2, 2, 4, 2, 4, 3]])

In [128]:
arr1[0]

array([4, 1, 1, 3, 2, 3])

In [129]:
arr1[1][2]

4

In [132]:
arr1[0,[1,3]]

array([1, 3])

In [133]:
arr1[0,[2,4]]

array([1, 2])

In [134]:
arr1[[2,4]]

array([[2, 3, 1, 1, 3, 1],
       [2, 2, 4, 2, 4, 3]])

In [135]:
arr1[2:4]

array([[2, 3, 1, 1, 3, 1],
       [3, 1, 2, 2, 1, 4]])

In [137]:
arr1[[2,4],[1,3]]

array([3, 2])

In [138]:
arr1[2:4,[1,3]]

array([[3, 1],
       [1, 2]])

In [27]:
arr1=np.random.randint(1,3,(3,3))

In [28]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
arr2=np.random.randint(1,3,(3,3))

In [142]:
arr2

array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 2]])

In [143]:
arr1-arr2

array([[-1, -1,  1],
       [ 1, -1, -1],
       [-1,  1,  0]])

In [144]:
arr1*arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 4]])

In [145]:
arr1/0

C:\Users\Pooja Rathore\AppData\Local\Temp\ipykernel_24680\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

## Brode casting

In [147]:
arr1

array([[1, 1, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [148]:
arr1+5

array([[6, 6, 7],
       [7, 6, 6],
       [6, 7, 7]])

In [6]:
a=np.array([1,2,3,4])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## Transform array

In [9]:
a.T                                                                          # ask question

array([1, 2, 3, 4])

In [10]:
a.T

array([1, 2, 3, 4])

In [11]:
arr+a.T

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [12]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
import numpy as np

In [14]:
arr=np.zeros((3,4))

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
## Broad casting

In [17]:
a

array([1, 2, 3, 4])

In [20]:
a=np.array([[1,2,3]])

In [21]:
a.T

array([[1],
       [2],
       [3]])

In [22]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a

array([[1, 2, 3]])

In [24]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [25]:
a.T


array([[1],
       [2],
       [3]])

In [26]:
a=np.array([1,2,3])

In [30]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])

In [32]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     ]])

In [33]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [34]:
a

array([1, 2, 3])

In [35]:
np.min(a)

1

In [36]:
np.max(a)

3

In [37]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
np.min(arr1)

1

In [39]:
arr1.T

array([[1, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [40]:
arr1.flatten()

array([1, 2, 1, 1, 1, 1, 1, 1, 1])

In [41]:
## expand_dims

In [54]:
arr=np.array([[1,2,3],[4,5,6],[1,2,3]])

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [44]:
np.sum(arr)

27

In [45]:
np.sum(arr,axis=0)

array([ 6,  9, 12])

In [46]:
np.sum(arr,axis=1)

array([ 6, 15,  6])

In [51]:
arr.ndim

2

In [56]:
arr1=np.expand_dims(arr, axis=0)

In [57]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]]])

In [58]:
arr1.ndim

3

In [59]:
arr2=np.expand_dims(arr1,axis=0)

In [60]:
arr2

array([[[[1, 2, 3],
         [4, 5, 6],
         [1, 2, 3]]]])

In [61]:
arr2.shape

(1, 1, 3, 3)

In [64]:
arr=np.zeros((3,4))

In [65]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr1=np.expand_dims(arr, axis=0)

In [70]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [71]:
arr1=np.expand_dims(arr, axis=1)

In [72]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])