In [110]:
import numpy as np
data=np.array([[1],[2],[3]])


In [111]:
data.ndim

2

In [112]:
data

array([[1],
       [2],
       [3]])

In [113]:
a=np.squeeze(data)

In [114]:
a

array([1, 2, 3])

In [115]:
a.ndim

1

In [116]:
# repeat

In [117]:
data

array([[1],
       [2],
       [3]])

In [118]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [119]:
a=np.array([[1,2],[3,4]])

In [120]:
a

array([[1, 2],
       [3, 4]])

In [121]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [124]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [125]:
data

array([[1],
       [2],
       [3]])

In [126]:
# roll
np.roll(data,-2)

array([[3],
       [1],
       [2]])

In [127]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [128]:
data

array([[1],
       [2],
       [3]])

In [129]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [130]:
#binary operation on array

In [131]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [132]:
arr1

array([[1, 2, 4, 1],
       [2, 1, 1, 4],
       [8, 7, 1, 8]])

In [133]:
arr2

array([[1, 8, 1, 7],
       [5, 7, 8, 1],
       [4, 1, 4, 4]])

In [134]:
arr1+arr2

array([[ 2, 10,  5,  8],
       [ 7,  8,  9,  5],
       [12,  8,  5, 12]])

In [135]:
arr1*arr2

array([[ 1, 16,  4,  7],
       [10,  7,  8,  4],
       [32,  7,  4, 32]])

In [136]:
arr1/arr2

array([[1.        , 0.25      , 4.        , 0.14285714],
       [0.4       , 0.14285714, 0.125     , 4.        ],
       [2.        , 7.        , 0.25      , 2.        ]])

In [137]:
arr1**arr2

array([[   1,  256,    4,    1],
       [  32,    1,    1,    4],
       [4096,    7,    1, 4096]])

In [138]:
arr1

array([[1, 2, 4, 1],
       [2, 1, 1, 4],
       [8, 7, 1, 8]])

In [139]:
arr2

array([[1, 8, 1, 7],
       [5, 7, 8, 1],
       [4, 1, 4, 4]])

In [140]:
arr1>arr2

array([[False, False,  True, False],
       [False, False, False,  True],
       [ True,  True, False,  True]])

In [141]:
~arr1

array([[-2, -3, -5, -2],
       [-3, -2, -2, -5],
       [-9, -8, -2, -9]])

In [142]:
arr1

array([[1, 2, 4, 1],
       [2, 1, 1, 4],
       [8, 7, 1, 8]])

In [143]:
#Numpy string function

In [144]:
arr = np.array(["pw","skills"])

In [145]:
arr

array(['pw', 'skills'], dtype='<U6')

In [146]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [147]:
np.char.lower(arr)

array(['pw', 'skills'], dtype='<U6')

In [148]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [149]:
#Mathematical function

arr1

array([[1, 2, 4, 1],
       [2, 1, 1, 4],
       [8, 7, 1, 8]])

In [150]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743, -0.7568025 ,  0.84147098],
       [ 0.90929743,  0.84147098,  0.84147098, -0.7568025 ],
       [ 0.98935825,  0.6569866 ,  0.84147098,  0.98935825]])

In [151]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.65364362,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231, -0.65364362],
       [-0.14550003,  0.75390225,  0.54030231, -0.14550003]])

In [152]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.60205999, 0.        ],
       [0.30103   , 0.        , 0.        , 0.60205999],
       [0.90308999, 0.84509804, 0.        , 0.90308999]])

In [153]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.71828183e+00],
       [7.38905610e+00, 2.71828183e+00, 2.71828183e+00, 5.45981500e+01],
       [2.98095799e+03, 1.09663316e+03, 2.71828183e+00, 2.98095799e+03]])

In [154]:
np.power(arr1,2)

array([[ 1,  4, 16,  1],
       [ 4,  1,  1, 16],
       [64, 49,  1, 64]], dtype=int32)

In [155]:
np.mean(arr1)

3.3333333333333335

In [156]:
np.max(arr1)

8

In [157]:
np.std(arr1)

2.7182510717166815

In [158]:
np.var(arr1)

7.388888888888888

In [159]:
arr1-arr2

array([[ 0, -6,  3, -6],
       [-3, -6, -7,  3],
       [ 4,  6, -3,  4]])

In [160]:
arr1*arr2

array([[ 1, 16,  4,  7],
       [10,  7,  8,  4],
       [32,  7,  4, 32]])

In [161]:
np.multiply(arr1,arr2)

array([[ 1, 16,  4,  7],
       [10,  7,  8,  4],
       [32,  7,  4, 32]])

In [162]:
np.mod(arr1,arr2)# return ele wise reminder

array([[0, 2, 0, 1],
       [2, 1, 1, 0],
       [0, 0, 1, 0]])

In [163]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 2.        , 1.        ],
       [1.41421356, 1.        , 1.        , 2.        ],
       [2.82842712, 2.64575131, 1.        , 2.82842712]])

In [164]:
## sort search

In [165]:
arr=np.array([5,6,1,2])

In [166]:
arr

array([5, 6, 1, 2])

In [167]:
np.sort(arr)

array([1, 2, 5, 6])

In [168]:
arr=np.array([5,6,100,200,1,2])

In [169]:
arr

array([  5,   6, 100, 200,   1,   2])

In [170]:
np.sort(arr)

array([  1,   2,   5,   6, 100, 200])

In [171]:
np.searchsorted(arr,3)

0

In [172]:
np.searchsorted(arr,3)

0

In [173]:
arr1=np.array([0,1,2,3,0,4])

In [174]:
np.count_nonzero(arr1)

4

In [175]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [176]:
arr1<1

array([ True, False, False, False,  True, False])

In [177]:
arr1

array([0, 1, 2, 3, 0, 4])

In [178]:
np.where(arr1>0)

(array([1, 2, 3, 5], dtype=int64),)

In [179]:
np.extract(arr1>0,arr1)

array([1, 2, 3, 4])

In [180]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [181]:
## matrix >> 2d array

In [182]:
import numpy.matlib as nm

In [183]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [184]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [185]:
#Numpy linear algebra

In [186]:
arr1

array([0, 1, 2, 3, 0, 4])

In [187]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [188]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [189]:
a =np.array(([7,5.3,-3],[3,-5,2],[5,3,-7]))

In [190]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [191]:
b =np.array([16,-8,0])

In [192]:
b

array([16, -8,  0])

In [193]:
np.linalg.solve(a,b)

array([0.90162081, 2.89483603, 1.88465888])

In [194]:
arr1

array([[2, 3],
       [4, 5]])

In [195]:
5*2-3*4

-2

In [196]:
np.linalg.det(arr1)

-2.0

In [197]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])